server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车区接口文档"
    package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true